"""Initial migration

Revision ID: 8777667ae3c0
Revises: 
Create Date: 2026-02-21 13:42:58.555974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8777667ae3c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=256), nullable=False),
    sa.Column('resource', sa.String(length=256), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cme_cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('radiologist_id', sa.String(length=64), nullable=False),
    sa.Column('digest_period', sa.String(length=32), nullable=True),
    sa.Column('case_json', sa.Text(), nullable=False),
    sa.Column('credit_points', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cme_cases_radiologist_id'), 'cme_cases', ['radiologist_id'], unique=False)
    op.create_table('feedback_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('radiologist_id', sa.String(length=64), nullable=False),
    sa.Column('correction_type', sa.String(length=64), nullable=False),
    sa.Column('correction_text', sa.Text(), nullable=False),
    sa.Column('learning_event_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_events_radiologist_id'), 'feedback_events', ['radiologist_id'], unique=False)
    op.create_index(op.f('ix_feedback_events_report_id'), 'feedback_events', ['report_id'], unique=False)
    op.create_table('followup_reminders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('study_id', sa.String(length=64), nullable=False),
    sa.Column('patient_token', sa.String(length=128), nullable=True),
    sa.Column('finding_id', sa.String(length=64), nullable=True),
    sa.Column('followup_type', sa.String(length=32), nullable=False),
    sa.Column('followup_modality', sa.String(length=32), nullable=True),
    sa.Column('followup_text', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followup_reminders_due_date'), 'followup_reminders', ['due_date'], unique=False)
    op.create_index(op.f('ix_followup_reminders_study_id'), 'followup_reminders', ['study_id'], unique=False)
    op.create_table('learning_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('radiologist_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=True),
    sa.Column('body_region', sa.String(length=64), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('report_text_before', sa.Text(), nullable=True),
    sa.Column('report_text_after', sa.Text(), nullable=True),
    sa.Column('qa_issues_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_events_event_type'), 'learning_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_learning_events_radiologist_id'), 'learning_events', ['radiologist_id'], unique=False)
    op.create_index(op.f('ix_learning_events_severity'), 'learning_events', ['severity'], unique=False)
    op.create_index(op.f('ix_learning_events_timestamp'), 'learning_events', ['timestamp'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('study_id', sa.String(length=64), nullable=True),
    sa.Column('radiologist_id', sa.String(length=64), nullable=True),
    sa.Column('modality', sa.String(length=16), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('key_findings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_radiologist_id'), 'reports', ['radiologist_id'], unique=False)
    op.create_index(op.f('ix_reports_study_id'), 'reports', ['study_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reports_study_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_radiologist_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_learning_events_timestamp'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_severity'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_radiologist_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_event_type'), table_name='learning_events')
    op.drop_table('learning_events')
    op.drop_index(op.f('ix_followup_reminders_study_id'), table_name='followup_reminders')
    op.drop_index(op.f('ix_followup_reminders_due_date'), table_name='followup_reminders')
    op.drop_table('followup_reminders')
    op.drop_index(op.f('ix_feedback_events_report_id'), table_name='feedback_events')
    op.drop_index(op.f('ix_feedback_events_radiologist_id'), table_name='feedback_events')
    op.drop_table('feedback_events')
    op.drop_index(op.f('ix_cme_cases_radiologist_id'), table_name='cme_cases')
    op.drop_table('cme_cases')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
